name: Dispatch Npm Publish

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [$default-branch]
        paths:
            - "**.js"
            - "**.ts"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    dispatch:
        runs-on: ubuntu-latest
        steps:
            - uses: adityakar/workflow-dispatcher@v1.0
              with:
                  owner: upradata
                  repo: .github
                  token: ${{ secrets.PAT }}
                  event_type: npm-publish
                  client_payload: '{"git-ref": "${{ github.event.inputs.git-ref }}"}'
                  wait_time: 5
                  max_time: 360
