name: Copy To Local package.json

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    repository_dispatch:
        types: [upradata/org-workflow]

jobs:
    update-package-json:
        runs-on: ubuntu-latest

        steps:
            # - name: Dump GitHub context
            #   env:
            #     GITHUB_CONTEXT: ${{ toJson(github) }}
            #   run: echo "$GITHUB_CONTEXT"

            - name: organization-centralized-workflows => Registration
              uses: upradata/organization-centralized-workflows.github-app@master
              with:
                  id: ${{ github.event.client_payload.id }}
                  callbackUrl: ${{ github.event.client_payload.callbackUrl }}
                  sha: ${{ github.event.client_payload.sha }}
                  runId: ${{ github.runId }}
                  name: ${{ github.workflow }}

            # Checkout repository
            - name: organization-centralized-workflows => Checkout
              run: |
                  PACKAGE_DIR=${{ github.event.client_payload.event.repository.name }}
                  mkdir $PACKAGE_DIR
                  cd $PACKAGE_DIR
                  git clone ${{ github.event.client_payload.event.repository.clone_url }}

              # uses: actions/checkout@v2.3.4
              # with:
              #     repository: ${{ github.event.client_payload.repository.fullName }}
              #     ref: ${{ github.event.client_payload.sha }}
              #     token: ${{ github.event.client_payload.token }}

            # Setup Node

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 15.9.0
                  check-latest: true
                  registry-url: "https://registry.npmjs.org"

            # Install pnpm

            - name: Create cache pnpm modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-pnpm-modules
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

            - name: Setup Pnpm
              run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6

            # install and run @upradata/npx-local

            - name: install @upradata/npx-local and execute
              run: |
                  pnpx --package @upradata/npx-local npx-local local-to-npm

            # transfer the new html files back into the repository

            - name: Commit files
              run: |
                  git config --local user.name ${{ github.event.client_payload.event.repository.owner.login }}
                  git config user.email ${{ github.event.client_payload.event.repository.owner.email }}
                  git add package.json
                  git commit -m "Updating package.json: copy local deps to npm dependencies"
                  git push

            # push the output folder to your repo

            # - name: Push changes
            #   uses: ad-m/github-push-action@master
            #   with:
            #       github_token: ${{ secrets.GITHUB_TOKEN }}
            #       force: true
